kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-efs-operator
subjects:
- kind: ServiceAccount
  name: aws-efs-operator
  # TODO(efried): Template this from config/config.go?
  namespace: openshift-aws-efs
roleRef:
  kind: ClusterRole
  name: aws-efs-operator
  apiGroup: rbac.authorization.k8s.io
