# permissions for end users to edit sharedvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharedvolume-editor-role
rules:
- apiGroups:
  - aws-efs.managed.openshift.io
  resources:
  - sharedvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-efs.managed.openshift.io
  resources:
  - sharedvolumes/status
  verbs:
  - get
